// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQLa-QX6r9k-R0tfmuQflbQR3Td_fMU94',
    appId: '1:430512220276:web:52f13bae8b8dc2d9784921',
    messagingSenderId: '430512220276',
    projectId: 'wellness-management-syst-8f17a',
    authDomain: 'wellness-management-syst-8f17a.firebaseapp.com',
    storageBucket: 'wellness-management-syst-8f17a.firebasestorage.app',
    measurementId: 'G-H3G124WW97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQQbqhgbT9arPjeaDafVQvfzvHjCBkRuE',
    appId: '1:430512220276:android:0ab551544e33dee3784921',
    messagingSenderId: '430512220276',
    projectId: 'wellness-management-syst-8f17a',
    storageBucket: 'wellness-management-syst-8f17a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYpG8zQy9KcAjRV0glZnmkgRLDgo-i3o0',
    appId: '1:430512220276:ios:4e882eae055750a6784921',
    messagingSenderId: '430512220276',
    projectId: 'wellness-management-syst-8f17a',
    storageBucket: 'wellness-management-syst-8f17a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYpG8zQy9KcAjRV0glZnmkgRLDgo-i3o0',
    appId: '1:430512220276:ios:4e882eae055750a6784921',
    messagingSenderId: '430512220276',
    projectId: 'wellness-management-syst-8f17a',
    storageBucket: 'wellness-management-syst-8f17a.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQLa-QX6r9k-R0tfmuQflbQR3Td_fMU94',
    appId: '1:430512220276:web:4b731d5c3a36d876784921',
    messagingSenderId: '430512220276',
    projectId: 'wellness-management-syst-8f17a',
    authDomain: 'wellness-management-syst-8f17a.firebaseapp.com',
    storageBucket: 'wellness-management-syst-8f17a.firebasestorage.app',
    measurementId: 'G-8MKMH3NJBH',
  );
}
