-- Fiuu payment-attempt ledger. The public checkout remains gated.
-- One attempt per booking token; Fiuu order ID is an unpredictable 128-bit ID
-- generated by the server. No wallet credentials or gateway keys are stored.

create table public.booking_payment_attempts (
  id uuid primary key default gen_random_uuid(),
  hold_token uuid not null,
  outlet_id uuid not null references public.outlets(id),
  gateway text not null default 'fiuu' check (gateway = 'fiuu'),
  merchant_id text not null,
  order_id text not null unique,
  amount numeric(12, 2) not null check (amount > 0),
  currency text not null default 'MYR' check (currency = 'MYR'),
  expires_at timestamptz not null,
  status text not null default 'created'
    check (status in ('created', 'pending', 'failed', 'confirmed',
                     'refund_required', 'refunded')),
  gateway_transaction_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create unique index booking_payment_attempts_fiuu_hold_token_uidx
  on public.booking_payment_attempts (hold_token);
create unique index booking_payment_attempts_fiuu_transaction_uidx
  on public.booking_payment_attempts (merchant_id, gateway_transaction_id)
  where gateway_transaction_id is not null;
create index booking_payment_attempts_outlet_id_idx
  on public.booking_payment_attempts (outlet_id);
create index booking_payment_attempts_unresolved_idx
  on public.booking_payment_attempts (status, created_at)
  where status in ('created', 'pending', 'refund_required');

alter table public.booking_payment_attempts enable row level security;
revoke all on public.booking_payment_attempts from public, anon, authenticated;
grant select, insert, update on public.booking_payment_attempts to service_role;

create function public.claim_fiuu_payment_attempt(
  p_token uuid,
  p_order_id text,
  p_merchant_id text,
  p_amount numeric,
  p_expires_at timestamptz
)
returns public.booking_payment_attempts
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_first public.booking_holds%rowtype;
  v_count integer := 0;
  v_amount numeric;
  v_expiry timestamptz;
  v_outlet_id uuid;
  v_existing public.booking_payment_attempts%rowtype;
  v_result public.booking_payment_attempts%rowtype;
begin
  if p_token is null or p_order_id !~ '^W[A-Za-z0-9]{32}$'
     or p_merchant_id !~ '^[A-Za-z0-9_-]{1,32}$' then
    raise exception 'Invalid Fiuu payment attempt';
  end if;

  -- Lock the complete group in stable order. The same hold locks serialize
  -- checkout, promotion mutation, and paid conversion without network I/O.
  for v_first in
    select h.* from public.booking_holds h
    where h.booking_group_token = p_token or h.public_token = p_token
    order by h.guest_index nulls first, h.id
    for update
  loop
    v_count := v_count + 1;
    if v_count = 1 then
      v_expiry := v_first.expires_at;
      v_outlet_id := v_first.outlet_id;
      v_amount := 0;
    end if;
    if v_first.status <> 'pending_payment' or v_first.expires_at <= now()
       or v_first.billplz_bill_id is not null then
      raise exception 'This booking hold cannot start Fiuu payment';
    end if;
    if v_first.expires_at is distinct from v_expiry then
      raise exception 'Booking group deadline is inconsistent';
    end if;
    if v_first.outlet_id is distinct from v_outlet_id then
      raise exception 'Booking group outlet is inconsistent';
    end if;
    v_amount := v_amount + v_first.total_amount;
  end loop;
  if v_count = 0 or round(v_amount, 2) is distinct from round(p_amount, 2)
     or v_expiry is distinct from p_expires_at then
    raise exception 'Fiuu payment quote does not match the held booking';
  end if;

  select * into v_existing from public.booking_payment_attempts
  where hold_token = p_token for update;
  if found then
    if v_existing.amount is distinct from round(p_amount, 2)
       or v_existing.expires_at is distinct from p_expires_at
       or v_existing.merchant_id is distinct from p_merchant_id then
      raise exception 'Existing Fiuu payment attempt has different terms';
    end if;
    return v_existing;
  end if;

  insert into public.booking_payment_attempts (
    hold_token, outlet_id, merchant_id, order_id, amount, expires_at
  ) values (
    p_token, v_outlet_id, p_merchant_id, p_order_id,
    round(p_amount, 2), p_expires_at
  ) returning * into v_result;
  return v_result;
end;
$function$;

revoke all on function public.claim_fiuu_payment_attempt(
  uuid, text, text, numeric, timestamptz
) from public, anon, authenticated;
grant execute on function public.claim_fiuu_payment_attempt(
  uuid, text, text, numeric, timestamptz
) to service_role;

create function public.prevent_fiuu_hold_quote_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if exists (
    select 1 from public.booking_payment_attempts a
    where a.hold_token = coalesce(old.booking_group_token, old.public_token)
  ) and (
    new.total_amount is distinct from old.total_amount
    or new.subtotal_amount is distinct from old.subtotal_amount
    or new.discount_amount is distinct from old.discount_amount
    or new.promotion_id is distinct from old.promotion_id
    or new.promotion_code_id is distinct from old.promotion_code_id
    or new.promotion_code is distinct from old.promotion_code
    or new.pricing_snapshot is distinct from old.pricing_snapshot
  ) then
    raise exception 'Booking pricing is locked after payment starts';
  end if;
  return new;
end;
$function$;

revoke all on function public.prevent_fiuu_hold_quote_change()
  from public, anon, authenticated;
create trigger prevent_fiuu_hold_quote_change
before update of total_amount, subtotal_amount, discount_amount,
  promotion_id, promotion_code_id, promotion_code, pricing_snapshot
on public.booking_holds
for each row execute function public.prevent_fiuu_hold_quote_change();
